<a href="https://colab.research.google.com/github/Ayeman985/Mini-project/blob/main/Project_Minor_ML_(Ayeman_Fatima).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install bing-image-downloader

In [2]:
import bing_image_downloader

In [3]:
!mkdir images

mkdir: cannot create directory ‘images’: File exists


In [4]:
from bing_image_downloader import downloader
downloader.download('red apple fruit', limit=20,  output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://wallpapercave.com/wp/2Cm4FW1.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://wallpapercave.com/wp/jLcYbhe.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://jooinn.com/images/red-apple-fruit-1.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://thumbs.dreamstime.com/b/red-apple-fruit-leaf-white-background-44829591.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.theayurveda.org/wp-content/uploads/2015/08/Apple-fruit.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://wallpapercave.com/wp/wp2722983.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?cs=srgb&amp;dl=apple-food-fruit-39803.jpg&amp;fm=jpg
[%] File Downloaded !

[%] Downloading Image #8 from http://mccutcheonsblog.files.wordpress.com/2011/09/red_delicious_apple.jpg
[%] File Downloaded !



In [5]:
from bing_image_downloader import downloader
downloader.download('watermelon fruit', limit=20,  output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://loseitapp.files.wordpress.com/2014/06/istock_000013512037large.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.chhajedgarden.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/0/d0e5watermelon21_1_.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://3.bp.blogspot.com/-YEisG3yXXrY/UrKYxXE8YHI/AAAAAAAAAHc/gaHfWqnTc28/s1600/Organic-Watermelon.bmp
[%] File Downloaded !

[%] Downloading Image #4 from https://img3.zakaz.ua/upload.version_1.0.f30cc96c455d83d00f1f18188740bf18.1350x1350.jpeg
[%] File Downloaded !

[%] Downloading Image #5 from http://www.kamdora.com/wp-content/uploads/2014/07/watermelon.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://3.bp.blogspot.com/-MTQNxVegI4A/UBbNjex2TmI/AAAAAAAAAPk/-VoCIYB6a1k/s1600/IMG_2199.JPG
[%] File Downloaded !

[%] Downloading Image #7 from http://4.bp.blogspot.com/-6nzONCEUnII/UC

In [6]:
import pandas as pd
import numpy as np
from skimage.transform import resize
from skimage.io import imread
import matplotlib.pyplot as plt
%matplotlib inline
import os

target = []
images = []   # In matrix format
flat_data = []  # In vector format

DATADIR = '/content/images'
CATEGORIES = ['red apple fruit','watermelon fruit']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

target = np.array(target)
images = np.array(images)
flat_data = np.array(flat_data)

In [7]:
# Creating a dataframe
import pandas as pd
df = pd.DataFrame(flat_data)
df['Target'] = target
df

0         1         2  ...     67498     67499  Target
0   0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
1   0.976471  0.976471  0.976471  ...  0.976471  0.976471       0
2   0.607843  0.164706  0.140980  ...  0.254314  0.123137       0
3   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
4   0.992157  0.996078  0.996078  ...  0.956863  0.992157       0
..       ...       ...       ...  ...       ...       ...     ...
61  1.000000  1.000000  1.000000  ...  0.976471  0.988235       1
62  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
63  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
64  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
65  0.592157  0.523529  0.403922  ...  0.370588  0.235294       1

[66 rows x 67501 columns]

In [8]:
cd /content/drive/My Drive

/content/drive/My Drive


In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
apple=df['Target']=='0'
watermelon=df['Target']=='1'

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)


In [11]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [12]:
df

0         1         2  ...     67498     67499  Target
0   0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
1   0.976471  0.976471  0.976471  ...  0.976471  0.976471       0
2   0.607843  0.164706  0.140980  ...  0.254314  0.123137       0
3   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
4   0.992157  0.996078  0.996078  ...  0.956863  0.992157       0
..       ...       ...       ...  ...       ...       ...     ...
61  1.000000  1.000000  1.000000  ...  0.976471  0.988235       1
62  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
63  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
64  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
65  0.592157  0.523529  0.403922  ...  0.370588  0.235294       1

[66 rows x 67501 columns]

In [13]:
X

array([[0.99215686, 0.99215686, 0.99215686, ..., 0.99215686, 0.99215686,
        0.99215686],
       [0.97647059, 0.97647059, 0.97647059, ..., 0.97647059, 0.97647059,
        0.97647059],
       [0.60784314, 0.16470588, 0.14098039, ..., 0.50686275, 0.25431373,
        0.12313725],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.59215686, 0.52352941, 0.40392157, ..., 0.24313725, 0.37058824,
        0.23529412]])

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
X_test.shape, X_train.shape, y_test.shape, y_train.shape

((14, 67500), (52, 67500), (14,), (52,))

In [17]:
X_test

array([[0.32941176, 0.05362092, 0.00784314, ..., 0.70200349, 0.57775163,
        0.46385272],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.52156863, 0.68169935, 0.87788671, ..., 0.39553377, 0.42810458,
        0.32222222],
       ...,
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.85490196, 0.83856209, 0.72156863, ..., 0.80522876, 0.78954248,
        0.63594771],
       [0.99215686, 0.99215686, 0.99215686, ..., 0.99215686, 0.99215686,
        0.99215686]])

In [18]:
X_train

array([[0.59215686, 0.52352941, 0.40392157, ..., 0.24313725, 0.37058824,
        0.23529412],
       [0.60784314, 0.16470588, 0.14098039, ..., 0.50686275, 0.25431373,
        0.12313725],
       [0.76433987, 0.87726797, 0.87846405, ..., 0.98431373, 0.98351634,
        0.98823529],
       ...,
       [0.57254902, 0.39607843, 0.3372549 , ..., 0.92352941, 0.87058824,
        0.83529412],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843]])

In [19]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1])

In [20]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1])

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]]


In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 1]
 [4 6]]


0.6428571428571429

In [25]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 4, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [26]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]]


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4 0]
 [3 7]]


0.7857142857142857

In [28]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [29]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]]


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 1]
 [4 6]]


0.6428571428571429

In [31]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [32]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 1]
 [5 5]]


0.5714285714285714

In [34]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 1]
 [2 8]]


0.7857142857142857

In [36]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 73.67 %
Standard Deviation: 16.36 %


In [37]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 83.33 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [38]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4 0]
 [1 9]]


0.9285714285714286

In [40]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 88.00 %
Standard Deviation: 13.27 %
